# Generated by Django 5.1.7 on 2025-03-25 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Military',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=200)),
                ('rank', models.CharField(choices=[('PVT', 'Private'), ('CPL', 'Corporal'), ('SGT', 'Sergeant'), ('ADT', 'Adjudant'), ('LT', 'Lieutenant'), ('CPT', 'Captain'), ('MAJ', 'Major'), ('COL', 'Colonel'), ('GEN', 'General')], max_length=3)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('current_unit', models.CharField(max_length=100)),
                ('service_number', models.CharField(max_length=100, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('is_maried', models.CharField(choices=[('M', 'MARIED'), ('S', 'SINGLE'), ('D', 'DIVORCED')], max_length=1)),
                ('graduation_school', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiel_of_study', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('diploma_number', models.CharField(max_length=50, unique=True)),
                ('type_of_diploma', models.CharField(choices=[('M', 'Military'), ('C', 'Civilian')], max_length=1)),
                ('graduation_date', models.DateField()),
                ('institution', models.CharField(max_length=100)),
                ('military', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='management_api.military')),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('military', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='management_api.military')),
            ],
        ),
    ]
